### PR TITLE
Make vim-plugin compatible with close-brackets behaviors.

### PR DESCRIPTION
**Pull request by TeachMeFly**
See [this discussion](https://github.com/LightTable/LightTable/pull/2093) for more info.

### CODE REVIEW

**Comment by kenny-evitt** [comment]
@TeachMeFly Is this still needed?

Was this intended to fix the behavior where, even if the auto-close-brackets was *disabled*, the Vim plugin was still inserting closing brackets?

**Comment by TeachMeFly** [comment]
@kenny-evitt yes, thats it.

**Comment by TeachMeFly** [comment]
@kenny-evitt, this issue appears when autoclose-brackets is enabled.

**Comment by kenny-evitt** [comment]
@TeachMeFly I'm confused. If auto-close-brackets is *enabled* why should the Vim plugin prevent a closing bracket from being inserted when an user enters an open bracket?

**Comment by TeachMeFly** [comment]
@kenny-evitt, it happends in vimMode, when you just open new tab and put cursor to some line . Pressing  '[' must cause jump to block before, but it insert '[]' brackets to code. If you enter insert mode and return back to vim mode, this bug disapear, and keys work as it should be.

**Comment by kenny-evitt** [comment]
@TeachMeFly Ahh; this happens in the Vim command mode. I'll check that. Would you add some very specific steps to reproduce this to the original issue so others can try to reproduce it too?

**Comment by cldwalker** [comment]
Confirmed this is an issue on .js and .cljs files and will merge + release shortly. This is a reasonable temporary fix. Once #45 lands we won't need this fix. See https://github.com/codemirror/CodeMirror/issues/2061

**Comment by cldwalker** [comment]
@TeachMeFly Thanks!

**Pull request merged**
